apiVersion: v1
kind: ConfigMap
metadata:
  name: mpi-hostfile
  namespace: default
data:
  hostfile: |
    mpi-pod-0 slots=2
    mpi-pod-1 slots=2
    mpi-pod-2 slots=2
    mpi-pod-3 slots=2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-cluster
  labels:
    app: mpi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mpi
  template:
    metadata:
      labels:
        app: mpi
    spec:
      containers:
      - name: mpi-container
        image: infaddil/hadoop-cluster-mpi:latest # Your Docker image
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"] # Keeps container alive for MPI jobs
        ports:
        - containerPort: 22 # SSH port for MPI
        volumeMounts:
        - name: mpi-hostfile-volume
          mountPath: /etc/mpi/hostfile
          subPath: hostfile
      volumes:
      - name: mpi-hostfile-volume
        configMap:
          name: mpi-hostfile # Reference to the ConfigMap
