version: "3"

services:
  namenode:
    image: amnrz/hadoop-namenode:v1
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    build:
      context: ./namenode
      dockerfile: Dockerfile

  datanode:
    image: amnrz/hadoop-datanode:v1
    container_name: datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    build:
      context: ./datanode
      dockerfile: Dockerfile

  resourcemanager:
    image: amnrz/hadoop-resourcemanager:v1
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    build:
      context: ./resourcemanager
      dockerfile: Dockerfile

  nodemanager1:
    image: amnrz/hadoop-nodemanager:v1
    container_name: nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    build:
      context: ./nodemanager
      dockerfile: Dockerfile

  historyserver:
    image: amnrz/hadoop-historyserver:v1
    container_name: historyserver
    restart: always
    ports:
      - 19888:19888
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    build:
      context: ./historyserver
      dockerfile: Dockerfile

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
